### ISSUE TITLE
Časová zóna

### ISSUE THREAD

**Issue by paveljanik** [GovCERT-CZ/hlaseniKBI#4]
Příloha č. 5 k vyhlášce č. 316/2014 Sb. uvádí položku Časová zóna. Ve vzorovém XML souboru ale tato uvedena není ani v XSD pro ni není definován typ.

XML soubor obsahuje:

``` xml
    <DiscoveryDate>2015-10-12T12:12:12</DiscoveryDate>
```

V datovém typu `dateTime` je možné vložit časovou zónu. Doporučuji se tedy rozhodnout zda:
- doplnit do XSD i položku pro časovou zónu
- doplnit do vzorového hlášení časovou zónu v elementu `DiscoveryDate` (a doplnit popis elementu `DiscoveryDate` v XSD, aby ohlašovatelé incidentů věděli, že mají použít plný formát včetně časové zóny)

Já preferuji druhou variantu (nebo ještě lépe hlášení s povinnou zónou Z, tedy UTC).

**Comment by tejk** [comment]
Doplnil jsem casovnou zonu do obou dokumentu. Vyzadovani zony, stejne jako ostatni zasahy do schematu vydam s dalsi verzi.

**Comment by paveljanik** [comment]
Díky.
