### ISSUE TITLE
Chybí informace o způsobu odeslání

### ISSUE THREAD

**Issue by paveljanik** [GovCERT-CZ/hlaseniKBI#6]
Myslím, že by zde měla být i zmínka o tom, jakým způsobem je možné finální, validovaný XML soubor odeslat, zda-li po odeslání přijde zpětná vazba a kam apod.

**Comment by paveljanik** [comment]
OK.

Pokud do commit message napíšete fixes #6, issue se samo zavře s commitem. Viz https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by tejk** [comment]
Super, diky za info.
